### ISSUE TITLE
 k4-lib crashing dedicated server on player login

### ISSUE THREAD

**Issue by kreezxil** [K-4U/k4lib#2]
Issue: k4-lib crashing dedicated server on player login

crash report:
https://gist.github.com/b00342da685b56a87525

fml server latest:
https://gist.github.com/c7e9c9513147ebefc3b8

**Comment by K-4U** [comment]
Suddenly realizing this ticket was actually made.. Do you still have issues with this?

**Comment by kreezxil** [comment]
Probably as out of no longer in my mega mod pack. If you have patched for the bug I'd be more than willing to try it in my mod pack again.

-----Original Message-----

**Comment by K-4U** [comment]
I have since released a couple of new versions, so it may be fixed, i honestly cannot tell at this moment. Could you try the latest versions?

**Comment by kreezxil** [comment]
What are the mods you have that depend on it?

-----Original Message-----

**Comment by K-4U** [comment]
Only K4Lib and colorchat would be required.

**Comment by kreezxil** [comment]
Ok that explains why I haven't bothered you further with it. I'm using tabbychat now.

-----Original Message-----
