### ISSUE TITLE
Crash on startup  (1.7.10)...

### ISSUE THREAD

**Issue by therealericbj** [K-4U/k4lib#4]
I attempted to try out your Fast Travel mod for 1.7.10.

Downloaded and installed the 2 files, fastTravel-1.7.10-1.0.2-universal.jar,  k4lib-1.7.10-0.1.57-universal.jar.

Started Minecraft client, it crashed, disabled the files and got this report from OpenEye...

http://openeye.openmods.info/crashes/167138712c0953de0f1caf8c81041538

...hope this helps find the issue, Happy Hunting.

**Comment by K-4U** [comment]
Fixed in https://github.com/K-4U/FastTravel/commit/4de4ed3db3e689e2be5ae67d593b0064a74a3395
Will update to curse asap.
