### ISSUE TITLE
K4lib causing crash when typing /help

### ISSUE THREAD

**Issue by Thoddius** [K-4U/k4lib#6]
I have tested both k4lib-1.7.10-0.1.55-universal and k4lib-1.7.10-0.1.57-universal with a clean forge-1.7.10-10.13.4.1566 and no other mods. See error report here: http://pastebin.com/GfJYiG1T.

With a clean Forge and only K4lib and HydCraft-1.7.10-2.1.249-universal, Forge tells me I need ForgeMultipart minimum of 1.1.0.297, which is not listed as a requirement on your site: http://minecraft.curseforge.com/projects/hydraulicraft.

After including ForgeMultipart-1.7.10-1.2.0.345-universal, and disabling RF from our previous conversation, I get this crash log: http://pastebin.com/LjMeTUa5.

**Comment by K-4U** [comment]
Is this issue still valid? I know i never replied on it, but i know i fixed stuff with regards to this..

**Comment by Thoddius** [comment]
I am not sure; It was 6 months ago. If I run into it again I will let you
know.

On Thu, Jun 23, 2016 at 4:45 AM, Koen Beckers notifications@github.com
wrote:

> Is this issue still valid? I know i never replied on it, but i know i
> fixed stuff with regards to this..
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/K-4U/k4lib/issues/6#issuecomment-228025689, or mute
> the thread
> https://github.com/notifications/unsubscribe/AQCzFzC1eDdAOTVBXTNu48uXujIhjBepks5qOnHpgaJpZM4HLHLM
> .

## 

Billy Mays is up in heaven partying like it's $19.99

**Comment by K-4U** [comment]
I know, i'm sorry.. Life caught up
