### ISSUE TITLE
/help kicks out of server

### ISSUE THREAD

**Issue by CHS7** [K-4U/k4lib#7]
When i use /help i get kicked with an error message 
![screen shot 2016-02-15 at 3 45 29 pm](https://cloud.githubusercontent.com/assets/16088440/13062250/b46aa9ba-d402-11e5-9ba8-068ec1118c5f.png)

Log
[fml-client-latest.log.zip](https://github.com/K-4U/k4lib/files/131572/fml-client-latest.log.zip)

@Mickimoo2

**Comment by Mickimoo** [comment]
@K-4U Here is the server log even though it doesn't show anything.

https://gist.github.com/Mickimoo2/d99ab4eab8a8b2b083b6

**Comment by kreezxil** [comment]
I'm getting this too when doing /help while connected to my server.

The server generates no crash logs for this.

The client pitches a fit and logs some stuff as seen here starting on line 3523 http://paste.ee/p/ZeAc3 but doesn't crash, so no official crash report.

**Comment by K-4U** [comment]
Is this issue still valid? I know i never replied on it, but i know i fixed stuff with regards to this..

**Comment by kreezxil** [comment]
I think you fixed it. it hasn't come up again. Yeah, you did fix it,
because you released an update right after I reported it and it didn't
happen again.

**Comment by K-4U** [comment]
Awesome :)
